Make the bot follow multiple users
codetheweb/aoede pull request #32
Opened 2022-12-08 09:42 UTC by baalajimaestro

Fixes https://github.com/codetheweb/aoede/issues/31

2022-12-08 10:14 UTC, sibartel requested changes
Thank you for your contribution. Some feedback my side.

2022-12-08 10:14 UTC, sibartel commented on src/main.rs
> +                        let mut channel_ids: Vec<Option<id::ChannelId>> = Vec::new();
Why do you use here an vector if in fact you only need one single channel_id later on?

Add the `is_some` check of line 142 as a condition to the if in 130 and only assign if a valid channel was found.
The var channel_id should then be an `Option<id::ChannelId>` initialized to `None`.

Then you can check if it is still None after your loop, if that's the case log that the 'admin' was not found. If it is some, join the channel.

2022-12-08 10:14 UTC, sibartel commented on src/main.rs
> +        let mut channel_ids: Vec<Option<id::ChannelId>> = Vec::new();
You only need one channel_id later on. Just use an `Option<id::ChannelId>`  and move the is_some() check into the loop in line 71.

2022-12-08 10:14 UTC, sibartel commented on src/main.rs
> +                player.lock().await.enable_connect().await;
Break here to prevent multiple connect attempts.

2022-12-08 10:14 UTC, sibartel commented on README.md
> +      - DISCORD_ADMINS=     # List (wrapped in single quotes) of users u want the bot to keep track of, eg value: '["100","200"]'
Personally I don't like the name `DISCORD_ADMINS`. Someone could think that he must list the discord server admins / owners here. Why not `DISCORD_USERS`?

2022-12-08 15:24 UTC, baalajimaestro commented
Thanks for the quick review, will resolve the requested changes

2024-06-08 20:26 UTC, Sheeley7 commented
Did any feature like this ever get merged into the main branch?

2026-06-10 06:51 UTC, closed without merging